### ISSUE TITLE
Line 70

### ISSUE THREAD

**Issue by BSardorbek** [Muhammadyusuf96/battery#1]
Traceback (most recent call last):
  File "C:\Users\Sardorbek\battery\battery.py", line 70, in <module>
    cwdth, _ = os.get_terminal_size()
ValueError: bad file descriptor

**Comment by BSardorbek** [comment]
shutil paketidan foydalansa bolar ekan

**Comment by BSardorbek** [comment]
endi line 117 da xatolik
Traceback (most recent call last):
  File "battery.py", line 117, in <module>
    timeleft = timedelta(seconds=battery.secsleft)
AttributeError: 'NoneType' object has no attribute 'secsleft'

**Comment by Muhammadyusuf96** [comment]
Bu qism faqat cmd.exe da ishlaydi
IDLE da shu xatolik chiqadi

**Comment by Muhammadyusuf96** [comment]
> endi line 117 da xatolik
> Traceback (most recent call last):
> File "battery.py", line 117, in
> timeleft = timedelta(seconds=battery.secsleft)
> AttributeError: 'NoneType' object has no attribute 'secsleft'

Bu shutildan foydalanganingizga emasmi?
